---
name: ✨ 기능 요청
about: 새로운 기능을 제안하거나 개선점을 제안합니다
title: "[Feature] "
labels: ["enhancement"]
assignees: ""

---

## ✅ 기능 설명
어떤 기능이 필요한지 명확하게 설명해주세요.

## 💡 기대 효과
이 기능이 왜 필요한지, 사용자에게 어떤 도움이 되는지 설명해주세요.

## 🔗 참고 자료
관련 문서, 링크, 이미지가 있다면 첨부해주세요.

## 📌 기타 의견
추가적으로 고려할 점이나 논의가 필요한 내용이 있다면 적어주세요.
