---
name: 🐛 버그 리포트
about: 동작하지 않는 기능에 대한 버그를 보고합니다
title: "[Bug] "
labels: ["bug"]
assignees: ""

---

## 🐞 버그 설명
무엇이 잘못되었는지 명확하고 간결하게 설명해주세요.

## 📍 재현 방법
동작이 재현되는 단계:
1. ...
2. ...
3. ...

## 🖥 기대 동작
정상적으로 어떤 동작이 되어야 하는지 설명해주세요.

## 🖼 스크린샷 (선택)
가능하다면 스크린샷을 첨부해주세요.

## 💻 환경 정보
- 브라우저/디바이스: 
- OS: 

## 📎 추가 정보
기타 참고 사항이 있다면 적어주세요.
